syntax = "proto3";

package registry.proto.group;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "peer/peer.proto";

option go_package = "github.com/uddinArsalan/ferry-proto/group";

service GroupService {
  rpc CreateGroup(CreateGroupRequest) returns (GroupID); // create group

  rpc GetGroupsForPeer(registry.proto.peer.PeerID) returns (Groups); // get groups of peer

  rpc GetGroups(google.protobuf.Empty) returns (Groups); // get groups of user

  rpc GetGroup(GroupID) returns (Group);
}

message CreateGroupRequest {
  string name = 1;
}

message GroupID {
  int64 id = 1;
}

message Group {
  int64 id = 1;
  string group_id = 2;
  string name = 3;
  int64 user_id = 4;
  google.protobuf.Timestamp created_at = 5;
}

message Groups {
  repeated Group groups = 1;
}
