syntax = "proto3";

import "google/protobuf/empty.proto"; 
import "google/protobuf/timestamp.proto"; 
import "peer/peer.proto";

package registry.proto.group;

option go_package = "github.com/uddinArsalan/ferry-proto/proto/group";

service GroupService {

  rpc CreateGroup(CreateGroupRequest) returns (Group); // create group

  rpc GetGroupsForPeer(peer.PeerID) returns (Groups); // get groups of peer

  rpc GetGroups(google.protobuf.Empty) returns (Groups); // get groups of user 

  rpc GetGroup(GroupID) returns (Group);
}

message CreateGroupRequest{
  string name = 1;
}

message GroupID {
  int64 id = 1;
}

message Group {
  int64 id = 1;
  string name = 2;
  google.protobuf.Timestamp created_at = 3;
}

message Groups {
  repeated Group groups = 1;
}